FROM jenkins/jenkins:2.426.3-jdk11

USER jenkins
RUN jenkins-plugin-cli --plugins \
  blueocean:1.27.16 \
  build-timestamp:1.0.3 \
  timestamper:1.17 \
  pollscm:1.3.1 \
  github-api:1.318-461.v7a_c09c9fa_d63 \
  json-path-api:2.8.0-5.v07cb_a_1ca_738c \
  token-macro:400.v35420b_922dcb_

USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

COPY ./requirements.txt requirements.txt

RUN apt update && \
    apt install -y python3 python3-pip
# Install required tools
RUN apt update && apt install -y python3.11 python3.11-venv python3-pip

# Create and activate a virtual environment
RUN python3 -m venv /opt/venv \
    && . /opt/venv/bin/activate \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

# Set the virtual environment in PATH for subsequent commands
ENV PATH="/opt/venv/bin:$PATH"

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
